name: PR Commenting Guidelines

on:
  pull_request:
    types:
      - opened

jobs:
  update_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Append commenting guidelines to PR description'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          current_pr_body=$(gh pr view $PR --json body --template {{.body}})
          separating_text=$'\n'$'\n'"---"$'\n'$'\n'
          text_to_append=$(cat .github/workflows/pr_guidelines_description.txt)
          gh pr edit $PR --body "$current_pr_body""$separating_text""$text_to_append"
